### ISSUE TITLE
suggestion - new dependency youtube_searcher

### ISSUE THREAD

**Issue by JarbasAl** [AIIX/youtube-skill#5]
you might want to look at https://github.com/HelloChatterbox/youtube_searcher

it extracts a json blob using minimal bs4 parsing, everything else is a dictionary lookup

results are more detailed, parsing is faster and less likely to break

**Comment by NeonDaniel** [comment]
I was just looking for a new search method as the existing html scrape method stopped working. I'll give this a try, thanks
